### Demonstração da biblioteca

In [2]:
import enigmalille
import numpy as np

In [8]:
matriz_one_hot = enigmalille.para_one_hot("mensagem de teste 01")
print(matriz_one_hot)
pos_one_hot = enigmalille.para_string(matriz_one_hot)
print(pos_one_hot)


[[0. 0. 0. 0. 1. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 1. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0. 0. 1. 0. 0. 0. 1. 0. 0. 1. 0. 0. 1. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 1. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [1. 0. 0. 0. 0. 0. 0. 1. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 1. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.

In [4]:
P = np.random.permutation(np.identity(38))
msg_cifrada = enigmalille.cifrar("mensagem de teste 02", P)
print(f"Mesagem cifrada: {msg_cifrada}")

msg_decifrada = enigmalille.de_cifrar(msg_cifrada, P)
print(f"Mesagem decifrada: {msg_decifrada}")

Mesagem cifrada: 3b cz4b38nb8abcab8dq
Mesagem decifrada: mensagem de teste 02


In [5]:
E = np.random.permutation(np.identity(38))
msg_enigma = enigmalille.enigma("mensagem de teste 03", P, E)
print(f"Mesagem cifrada com engima: {msg_enigma}")

msg_de_enigma = enigmalille.de_enigma(msg_enigma, P, E)
print(f"Mensagem decifrada com enigma: {msg_de_enigma}")

Mesagem cifrada com engima: 3cpmb7efz6zsasca8i_g
Mensagem decifrada com enigma: mensagem de teste 03


**mensagem com caracteres que não fazem parte do alfabeto**

In [6]:
msg_enigma = enigmalille.enigma("caracteres estranhos: @¨&($*#_)", P, E)
print(f"Mesagem cifrada com engima: {msg_enigma}")

msg_de_enigma = enigmalille.de_enigma(msg_enigma, P, E)
print(f"Mensagem decifrada com enigma: {msg_de_enigma}")

Mesagem cifrada com engima: ppwscae5gzkpsawppr0ef 96oyuxq_l
Mensagem decifrada com enigma: caracteres estranhos_ _________


**mensagem vazia**

In [7]:
msg_enigma = enigmalille.enigma("", P, E)
print(f"Mesagem cifrada com engima: {msg_enigma}")

msg_de_enigma = enigmalille.de_enigma(msg_enigma, P, E)
print(f"Mensagem decifrada com enigma: {msg_de_enigma}")

Mesagem cifrada com engima: 
Mensagem decifrada com enigma: 
